<?php

/**
 * This is the model base class for the table "profiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Profiles".
 *
 * Columns in table "profiles" available as properties of the model,
 * followed by relations of table "profiles" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $location_id
 * @property string $first_name
 * @property string $last_name
 * @property string $about_yourself
 * @property string $photo
 * @property string $mobile_number
 * @property integer $gender
 * @property string $date_of_birth
 * @property string $public_url
 *
 * @property Locations $location
 * @property Users $user
 */
abstract class BaseProfiles extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'profiles';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Profiles|Profiles', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('first_name', 'required'),
			array('user_id, location_id, gender', 'numerical', 'integerOnly'=>true),
			array('first_name, last_name, photo', 'length', 'max'=>45),
			array('about_yourself', 'length', 'max'=>150),
			array('mobile_number', 'length', 'max'=>13),
			array('public_url', 'length', 'max'=>100),
			array('date_of_birth', 'safe'),
			array('first_name, last_name, about_yourself, photo, mobile_number, gender, date_of_birth, public_url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, location_id, first_name, last_name, about_yourself, photo, mobile_number, gender, date_of_birth, public_url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'location' => array(self::BELONGS_TO, 'Locations', 'location_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'location_id' => null,
			'first_name' => Yii::t('app', 'First Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'about_yourself' => Yii::t('app', 'About Yourself'),
			'photo' => Yii::t('app', 'Photo'),
			'mobile_number' => Yii::t('app', 'Mobile Number'),
			'gender' => Yii::t('app', 'Gender'),
			'date_of_birth' => Yii::t('app', 'Date Of Birth'),
			'public_url' => Yii::t('app', 'Public Url'),
			'location' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('about_yourself', $this->about_yourself, true);
		$criteria->compare('photo', $this->photo, true);
		$criteria->compare('mobile_number', $this->mobile_number, true);
		$criteria->compare('gender', $this->gender);
		$criteria->compare('date_of_birth', $this->date_of_birth, true);
		$criteria->compare('public_url', $this->public_url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}