<?php

/**
 * This is the model base class for the table "cities".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Cities".
 *
 * Columns in table "cities" available as properties of the model,
 * followed by relations of table "cities" available as properties of the model.
 *
 * @property integer $id
 * @property integer $state_id
 * @property string $city_name
 * @property integer $status
 * @property string $update_time
 * @property string $create_time
 * @property string $created_by
 * @property string $updated_by
 *
 * @property States $state
 * @property Locations[] $locations
 */
abstract class BaseCities extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cities';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Cities|Cities', $n);
	}

	public static function representingColumn() {
		return 'city_name';
	}

	public function rules() {
		return array(
			array('state_id', 'required'),
			array('state_id, status', 'numerical', 'integerOnly'=>true),
			array('city_name, created_by, updated_by', 'length', 'max'=>45),
			array('update_time, create_time', 'safe'),
			array('city_name, status, update_time, create_time, created_by, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, state_id, city_name, status, update_time, create_time, created_by, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'state' => array(self::BELONGS_TO, 'States', 'state_id'),
			'locations' => array(self::HAS_MANY, 'Locations', 'city_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'state_id' => null,
			'city_name' => Yii::t('app', 'City Name'),
			'status' => Yii::t('app', 'Status'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_time' => Yii::t('app', 'Create Time'),
			'created_by' => Yii::t('app', 'Created By'),
			'updated_by' => Yii::t('app', 'Updated By'),
			'state' => null,
			'locations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('city_name', $this->city_name, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('created_by', $this->created_by, true);
		$criteria->compare('updated_by', $this->updated_by, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}