<?php

/**
 * This is the model base class for the table "locations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Locations".
 *
 * Columns in table "locations" available as properties of the model,
 * followed by relations of table "locations" available as properties of the model.
 *
 * @property integer $id
 * @property integer $state_id
 * @property integer $city_id
 * @property string $locality_name
 * @property string $create_time
 * @property string $update_time
 * @property integer $status
 *
 * @property Cities $city
 * @property States $state
 * @property Profiles[] $profiles
 */
abstract class BaseLocations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'locations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Locations|Locations', $n);
	}

	public static function representingColumn() {
		return 'locality_name';
	}

	public function rules() {
		return array(
			array('state_id, city_id', 'required'),
			array('state_id, city_id, status', 'numerical', 'integerOnly'=>true),
			array('locality_name', 'length', 'max'=>100),
			array('create_time, update_time', 'safe'),
			array('locality_name, create_time, update_time, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, state_id, city_id, locality_name, create_time, update_time, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'city' => array(self::BELONGS_TO, 'Cities', 'city_id'),
			'state' => array(self::BELONGS_TO, 'States', 'state_id'),
			'profiles' => array(self::HAS_MANY, 'Profiles', 'location_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'state_id' => null,
			'city_id' => null,
			'locality_name' => Yii::t('app', 'Locality Name'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'status' => Yii::t('app', 'Status'),
			'city' => null,
			'state' => null,
			'profiles' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('locality_name', $this->locality_name, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}