<?php

/**
 * This is the model base class for the table "states".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "States".
 *
 * Columns in table "states" available as properties of the model,
 * followed by relations of table "states" available as properties of the model.
 *
 * @property integer $id
 * @property string $state_name
 * @property string $create_time
 * @property string $update_time
 * @property integer $status
 * @property string $created_by
 * @property string $updated_by
 *
 * @property Cities[] $cities
 * @property Locations[] $locations
 */
abstract class BaseStates extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'states';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'States|States', $n);
	}

	public static function representingColumn() {
		return 'state_name';
	}

	public function rules() {
		return array(
			array('status', 'numerical', 'integerOnly'=>true),
			array('state_name', 'length', 'max'=>100),
			array('created_by, updated_by', 'length', 'max'=>45),
			array('create_time, update_time', 'safe'),
			array('state_name, create_time, update_time, status, created_by, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, state_name, create_time, update_time, status, created_by, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cities' => array(self::HAS_MANY, 'Cities', 'state_id'),
			'locations' => array(self::HAS_MANY, 'Locations', 'state_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'state_name' => Yii::t('app', 'State Name'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'status' => Yii::t('app', 'Status'),
			'created_by' => Yii::t('app', 'Created By'),
			'updated_by' => Yii::t('app', 'Updated By'),
			'cities' => null,
			'locations' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('state_name', $this->state_name, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('created_by', $this->created_by, true);
		$criteria->compare('updated_by', $this->updated_by, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}