<?php

/**
 * This is the model base class for the table "guides".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Guides".
 *
 * Columns in table "guides" available as properties of the model,
 * followed by relations of table "guides" available as properties of the model.
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $location_id
 * @property integer $photo_id
 * @property string $guide_name
 * @property string $about_yourself
 * @property integer $gender
 * @property string $mobile_number
 * @property string $experience_detail
 * @property integer $status
 *
 * @property Photos $photo
 * @property Users $user
 */
abstract class BaseGuides extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'guides';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Guides|Guides', $n);
	}

	public static function representingColumn() {
		return 'guide_name';
	}

	public function rules() {
		return array(
			array('user_id, location_id, photo_id', 'required'),
			array('user_id, location_id, photo_id, gender, status', 'numerical', 'integerOnly'=>true),
			array('guide_name, experience_detail', 'length', 'max'=>45),
			array('about_yourself', 'length', 'max'=>150),
			array('mobile_number', 'length', 'max'=>13),
			array('guide_name, about_yourself, gender, mobile_number, experience_detail, status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, location_id, photo_id, guide_name, about_yourself, gender, mobile_number, experience_detail, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'photo' => array(self::BELONGS_TO, 'Photos', 'photo_id'),
			'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'location_id' => Yii::t('app', 'Location'),
			'photo_id' => null,
			'guide_name' => Yii::t('app', 'Guide Name'),
			'about_yourself' => Yii::t('app', 'About Yourself'),
			'gender' => Yii::t('app', 'Gender'),
			'mobile_number' => Yii::t('app', 'Mobile Number'),
			'experience_detail' => Yii::t('app', 'Experience Detail'),
			'status' => Yii::t('app', 'Status'),
			'photo' => null,
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('photo_id', $this->photo_id);
		$criteria->compare('guide_name', $this->guide_name, true);
		$criteria->compare('about_yourself', $this->about_yourself, true);
		$criteria->compare('gender', $this->gender);
		$criteria->compare('mobile_number', $this->mobile_number, true);
		$criteria->compare('experience_detail', $this->experience_detail, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}